apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: efs.filesystem.flexops.io
spec:
  group: filesystem.flexops.io
  names:
    kind: XAmazonEfs        # cluster scope type
    plural: xamazonefss
  claimNames:               # namespace scope type
    kind: amazonEfs
    plural: amazonefss            # lowercase only

  versions:
    - name: v1alpha1
      additionalPrinterColumns:
      - jsonPath: .status.conditions[?(@.type=='Ready')].status
        name: READY
        type: string
      - jsonPath: .status.conditions[?(@.type=='Synced')].status
        name: SYNCED
        type: string
      - jsonPath: .metadata.creationTimestamp
        name: AGE
        type: date
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  description: EFS Input Parameters
                  type: object
                  properties:

                    AZName:
                      description: AWS AZ
                      type: string
                    backup:
                      description: Enable automatic backups?
                      type: boolean
                      default: false
                    encrypted:
                      description: Encrypt the file system?
                      type: boolean
                      default: true
                    kmsKeyID:
                      description: ID/ARN/Alias of KMS Key (Leave blank to use default EKS Key)
                      type: string
                    performanceMode:
                      description: Mode - generalPurpose / maxIO
                      type: string
                      default: generalPurpose
                    provisionedMibps:
                      description: Measured throughput for provisioned mode (1 - 1024)
                      type: integer
                    throughputMode:
                      description: Mode - bursting or provisioned
                      type: string
                      default: bursting
                  required:
                    - AZName
                resourceConfig:
                  description: ResourceConfig defines general properties of this AWS
                    resource.
                  type: object
                  properties:

                    deletionPolicy:
                      description: Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                      type: string
                      name:
                        description: Set the name of this resource in AWS to the value
                          provided by this field.
                        type: string
                    providerConfigName:
                      type: string
                    region:
                      type: string

                  required:
                    - providerConfigName
                    - region
              required:
                - parameters
                - resourceConfig
          required:
            - spec
